version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-clone
    ports:
      - 8080:80

  nginx:
    image: nginx:alpine
    container_name: nginx_app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
